version: '3.9'

services:
  app:
    container_name: moviesapi
    build: .
    restart: always
    ports:
      - "8080:3000"
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: catalog
      DB_USERNAME: postgres
      DB_PASSWORD: senha

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    
    
